---
inputType: "CA10__CaAwsLoadBalancer__c"
importExtracts:
  - file: "/types/CA10__CaAwsLoadBalancer__c/object.extracts.yaml"
testData:
  - file: "test-data.json"
conditions:
  - status: "INCOMPLIANT"
    currentStateMessage: "The load balancer is registered in only one Availability Zone."
    remediationMessage: "Add at least one more Availability Zone to the load balancer to improve fault tolerance."
    check:
      LESS_THAN:
        left:
          SIZE:
            arg:
              EXTRACT: "caSetFrom_availabilityZones__c"
        right:
          NUMBER: 2
otherwise:
  status: "COMPLIANT"
  currentStateMessage: "The load balancer is registered across multiple Availability Zones."