---
inputObject: "CA10Z1__CaAzureMySqlServer__c"
testData:
  - file: "test-data.json"
importExtracts:
  - file: "/types/CA10Z1__CaAzureMySqlServer__c/object.extracts.yaml"
conditions:
  - status: "INAPPLICABLE"
    currentStateMessage: "This is not the Flexible Server deployment mode."
    condition:
      NOT_EQUAL:
        left:
          EXTRACT: "CA10Z1__deploymentMode__c"
        right:
          TEXT: "Flexible"
  - status: "INCOMPLIANT"
    currentStateMessage: "MySQL Flexible Server audit_log_enabled configuration parameter is disabled."
    remediationMessage: "Consider enabling MySQL Flexible Server audit_log_enabled configuration."
    condition:
      IS_EQUAL:
        left:
          JSON_QUERY_TEXT:
              arg: 
                EXTRACT: "caJsonFrom__configurations__c"
              expression: "[? name == 'audit_log_enabled'].value | [0]"
              undeterminedIf: 
                evaluationError: "The JSON query has failed."
                resultTypeMismatch: "The JSON query did not return text type."
        right:
          TEXT: "off"
  - status: "INCOMPLIANT"
    currentStateMessage: "MySQL Flexible Server audit_log_events configuration parameter is not set to CONNECTION."
    remediationMessage: "Consider setting MySQL Flexible Server audit_log_events configuration to CONNECTION."
    condition:
      AND:
        args:
        - IS_EQUAL:
            left:
              JSON_QUERY_TEXT:
                  arg: 
                    EXTRACT: "caJsonFrom__configurations__c"
                  expression: "[? name == 'audit_log_enabled'].value | [0]"
                  undeterminedIf: 
                    evaluationError: "The JSON query has failed."
                    resultTypeMismatch: "The JSON query did not return text type."
            right:
              TEXT: "on"
        - NOT_EQUAL:
            left:
              JSON_QUERY_TEXT:
                  arg: 
                    EXTRACT: "caJsonFrom__configurations__c"
                  expression: "[? name == 'audit_log_events'].value | [0]"
                  undeterminedIf: 
                    evaluationError: "The JSON query has failed."
                    resultTypeMismatch: "The JSON query did not return text type."
            right:
              TEXT: "CONNECTION"
  - status: "COMPLIANT"
    currentStateMessage: "MySQL Flexible Server audit_log_events configuration parameter is set to CONNECTION."
    condition:
      AND:
        args:
        - IS_EQUAL:
            left:
              JSON_QUERY_TEXT:
                  arg: 
                    EXTRACT: "caJsonFrom__configurations__c"
                  expression: "[? name == 'audit_log_enabled'].value | [0]"
                  undeterminedIf: 
                    evaluationError: "The JSON query has failed."
                    resultTypeMismatch: "The JSON query did not return text type."
            right:
              TEXT: "on"
        - IS_EQUAL:
            left:
              JSON_QUERY_TEXT:
                  arg: 
                    EXTRACT: "caJsonFrom__configurations__c"
                  expression: "[? name == 'audit_log_events'].value | [0]"
                  undeterminedIf: 
                    evaluationError: "The JSON query has failed."
                    resultTypeMismatch: "The JSON query did not return text type."
            right:
              TEXT: "CONNECTION"
otherwise:
  status: "UNDETERMINED"
  currentStateMessage: "Unexpected value in the field."