---
inputObject: "CA10__CaAwsApiGatewayRestApi__c"
testData:
  - file: test-data.json
conditions:
  - status: "INCOMPLIANT"
    currentStateMessage: "There is at least one related API Stage where CloudWatch Logs are not enabled."
    remediationMessage: "Consider enabling CloudWatch Logs for the API Stage."
    condition:
      RELATED_LIST_HAS:
        relationshipName: "CA10__AWS_API_Gateway_Stages__r"
        status: "INCOMPLIANT"
otherwise:
  status: "COMPLIANT"
  currentStateMessage: "API is compliant"
relatedLists:
  - relationshipName: "CA10__AWS_API_Gateway_Stages__r"
    conditions:
      - status: "INCOMPLIANT"
        currentStateMessage: "CloudWatch Logs are not enabled for this API Stage."
        remediationMessage: "Consider enabling CloudWatch Logs for this API Stage."
        condition:
          IS_EMPTY:
            arg:
              FIELD: 
                path: "CA10__cloudWatchLogLevel__c"
    otherwise:
      status: "COMPLIANT"
      currentStateMessage: "Stage is compliant"
