---
inputObject: "CA10Z1__CaAzureMySqlServer__c"
testData:
  - file: "test-data.json"
importExtracts:
  - file: "/types/CA10Z1__CaAzureMySqlServer__c/object.extracts.yaml"
conditions:
  - status: "INCOMPLIANT"
    currentStateMessage: "MySQL Server SSL Enforcement is disabled."
    remediationMessage: "Consider enabling MySQL Server SSL Enforcement."
    condition:
      IS_EQUAL:
        left:
          EXTRACT: "CA10Z1__sslEnforcement__c"
        right:
          TEXT: "Disabled"
  - status: "COMPLIANT"
    currentStateMessage: "MySQL Server SSL Enforcement is enabled."
    condition:
      IS_EQUAL:
        left:
          EXTRACT: "CA10Z1__sslEnforcement__c"
        right:
          TEXT: "Enabled"
otherwise:
  status: "UNDETERMINED"
  currentStateMessage: "Unexpected value in the field."