---
inputType: "CA10__CaAzureKeyVault__c"
importExtracts:
  - file: "/types/CA10__CaAzureKeyVault__c/object.extracts.yaml"
testData:
  - file: "test-data.json"
conditions:
  - status: "INCOMPLIANT"
    currentStateMessage: "The Purge Protection is disabled."
    remediationMessage: "Consider enabling Purge Protection function."
    check:
      NOT_EQUAL:
        left:
          EXTRACT: "CA10__purgeProtection__c"
        right:
          TEXT: "Enabled"
  - status: "COMPLIANT"
    currentStateMessage: "The Purge Protection function is enabled."
    check:
      IS_EQUAL:
        left:
          EXTRACT: "CA10__purgeProtection__c"
        right:
          TEXT: "Enabled"
otherwise:
  status: "UNDETERMINED"
  currentStateMessage: "Unexpected values in the fields."
