---
inputObject: "CA10Z1__CaAzureMySqlServer__c"
testData:
  - file: "test-data.json"
importExtracts:
  - file: "/types/CA10Z1__CaAzureMySqlServer__c/object.extracts.yaml"
conditions:
  - status: "INCOMPLIANT"
    currentStateMessage: "MySQL Server TLS Enforcement is disabled."
    remediationMessage: "Consider enabling MySQL Server TLS Enforcement."
    condition:
      IS_EQUAL:
        left:
          EXTRACT: "CA10Z1__minimalTlsVersion__c"
        right:
          TEXT: "TLSEnforcementDisabled"
  - status: "INCOMPLIANT"
    currentStateMessage: "MySQL Server uses legacy protocol TLS 1.0."
    remediationMessage: "Consider setting 'Minimum TLS version' to TLS 1.2."
    condition:
      IS_EQUAL:
        left:
          EXTRACT: "CA10Z1__minimalTlsVersion__c"
        right:
          TEXT: "TLS1_0"
  - status: "INCOMPLIANT"
    currentStateMessage: "MySQL Server uses legacy protocol TLS 1.1."
    remediationMessage: "Consider setting 'Minimum TLS version' to TLS 1.2."
    condition:
      IS_EQUAL:
        left:
          EXTRACT: "CA10Z1__minimalTlsVersion__c"
        right:
          TEXT: "TLS1_1"    
  - status: "COMPLIANT"
    currentStateMessage: "The 'Minimum tls version' is set to TLS 1.2."
    condition:
      IS_EQUAL:
        left:
          EXTRACT: "CA10Z1__minimalTlsVersion__c"
        right:
          TEXT: "TLS1_2"
otherwise:
  status: "UNDETERMINED"
  currentStateMessage: "Unexpected value in the field."