---
inputObject: "CA10__CaAwsUser__c"
testData:
  - file: test-data.json
importExtracts:
  - file: /types/CA10__CaAwsUser__c/credReport.extracts.yaml
conditions:
  - status: "INAPPLICABLE"
    currentStateMessage: "Requirements of this policy are applicable only to users\
      \ with enabled console password"
    condition:
      IS_EQUAL:
        left:
          EXTRACT: caExtract_credReport_password_enabled__c
        right:
          BOOLEAN: false
  - status: "COMPLIANT"
    currentStateMessage: "MFA Enabled for this user"
    condition:
      IS_EQUAL:
        left:
          EXTRACT: caExtract_credReport_mfa_active__c
        right:
          BOOLEAN: true
otherwise:
  status: "INCOMPLIANT"
  currentStateMessage: "MFA is not enabled for this user"
  remediationMessage: "Enable MFA for this user or disable the console access"