---
inputObject: "CA10__CaAwsAutoScalingGroup__c"
conditions:
  - status: "INCOMPLIANT"
    currentStateMessage: "There is at least one incompliant related Load Balancer"
    remediationMessage: "Fix the related incompliant Load Balancer"
    condition:
      RELATED_LIST_HAS:
        relationshipName: "CA10__AWS_EC2_Auto_Scaling_Group_LB_Links__r"
        status: "INCOMPLIANT"
  - status: "UNDETERMINED"
    currentStateMessage: "There are related objects with undetermined status"
    condition:
      RELATED_LIST_HAS:
        relationshipName: "CA10__AWS_EC2_Auto_Scaling_Group_LB_Links__r"
        status: "UNDETERMINED"
otherwise:
  status: "COMPLIANT"
  currentStateMessage: "Auto Scaling group is compliant"
relatedLists:
  - relationshipName: "CA10__AWS_EC2_Auto_Scaling_Group_LB_Links__r"
    importExtracts:
      - file: /types/CA10__CaAwsAutoScalingGroup__c/object.extracts.yaml
      - file: /types/CA10__CaAwsLoadBalancer__c/object.extracts.yaml
    conditions:
      - status: "INCOMPLIANT"
        currentStateMessage: "The set of Availability Zones configured on the Auto\
          \ Scaling Group does not match the set configured on Load Balancer"
        remediationMessage: "Adjust the set of Availability Zones either on the Auto\
          \ Scaling Group or the Load Balancer to match"
        condition:
          NOT_EQUAL:
            left:
              EXTRACT: "CA10__autoScalingGroup__r.caExtract_availabilityZones_asCollection__c"
            right:
              EXTRACT: "CA10__loadBalancer__r.caExtract_availabilityZones_asCollection__c"
    otherwise:
      status: "COMPLIANT"
      currentStateMessage: "Load balancer has the same availability zones as Auto\
        \ Scaling Group"
